add home work for JS
dtyta/js-lectures pull request #1
Opened 2023-05-03 14:37 UTC by dtyta

2023-05-08 09:54 UTC, SanitarskyiDmytro requested changes

2023-05-08 09:54 UTC, SanitarskyiDmytro commented on home-work-js.js
> + if(price <1000){
Тут потрібно обʼєднати умови між собою, щоб вони були в одних дужках.
```
if(...){
console.log("значення ціни товару знаходиться між 1000 та 1900")
}
else { 
    console.log("значення ціни товару НЕ знаходиться між 1000 та 1900")
}
```

2023-05-08 09:54 UTC, SanitarskyiDmytro commented on home-work-js.js
> + if(price <1000){
Все працює як потрібно, просто код скоротиться)

2023-05-08 09:54 UTC, SanitarskyiDmytro commented on home-work-js.js
> +if(price1 >1000){
а тут потрібно обʼєднати умови між собою, щоб вони були в одних дужках, як в коментарі вище, бо код не працює як потрібно(

2023-05-08 09:54 UTC, SanitarskyiDmytro commented on home-work-js.js
> +console.log(text.replace(/[ioo]/gi, ''))
потрібно додати усі голосні, щоб цей код працював для будь-якого тексту

2023-05-08 17:31 UTC, dtyta commented
Remarks fixed

2023-05-08 17:32 UTC, dtyta commented
@SanitarskiyDima  pls check HW  v.2.0

2023-05-10 18:13 UTC, dtyta commented
@SanitarskiyDima  pls check HW. Function was added.

2023-05-11 13:29 UTC, SanitarskyiDmytro approved these changes

2023-05-25 18:43 UTC, merged